stages:

  data_ingestion:
    cmd: python models/movie_genre/data_ingestion.py
    deps:
      - models/movie_genre/data_ingestion.py
      - src/connections/mongodb_connection.py
      - params.yaml
    outs:
      - data/movie_genre/raw/train.csv
      - data/movie_genre/raw/test.csv


  data_preprocessing:
    cmd: python models/movie_genre/data_preprocessing.py
    deps:
      - models/movie_genre/data_preprocessing.py
      - data/movie_genre/raw/train.csv
      - data/movie_genre/raw/test.csv
    outs:
      - data/movie_genre/interim/train_processed.csv
      - data/movie_genre/interim/test_processed.csv


  feature_engineering:
    cmd: python models/movie_genre/feature_engineering.py
    deps:
      - models/movie_genre/feature_engineering.py
      - data/movie_genre/interim/train_processed.csv
      - data/movie_genre/interim/test_processed.csv
      - params.yaml
    outs:
      - data/movie_genre/processed/train_tfidf.csv
      - data/movie_genre/processed/test_tfidf.csv
      - models/movie_genre/vectorizer.pkl


  model_building:
    cmd: python models/movie_genre/model_building.py
    deps:
      - models/movie_genre/model_building.py
      - data/movie_genre/processed/train_tfidf.csv
      - models/movie_genre/vectorizer.pkl
      - params.yaml
    outs:
      - models/movie_genre/model.pkl


  model_evaluation:
    cmd: python models/movie_genre/model_evaluation.py
    deps:
      - models/movie_genre/model_evaluation.py
      - models/movie_genre/model.pkl
      - data/movie_genre/processed/test_tfidf.csv
    outs:
      - reports/metrics.json
      - reports/experiment_info.json
