stages:

  # -------------------------------------------------
  # DATA INGESTION (shared logic, all models)
  # -------------------------------------------------
  data_ingestion:
    foreach:
      # - fraud_detection
      - movie_genre
      # - customer_churn
      - spam_sms
    do:
      cmd: python models/${item}/src/data_ingestion.py
      deps:
        - models/${item}/src/data_ingestion.py
        - connections/mongo_connection.py
        - params.yaml
      params:
        - global.random_state
        - global.mongodb
        - models.${item}.data_ingestion
      outs:
        - data/${item}/raw


  # -------------------------------------------------
  # DATA PREPROCESSING (shared logic, all models)
  # -------------------------------------------------
  data_preprocessing:
    foreach:
      # - fraud_detection
      - movie_genre
      # - customer_churn
      - spam_sms
    do:
      cmd: python models/${item}/src/data_preprocessing.py
      deps:
        - models/${item}/src/data_preprocessing.py
        - data/${item}/raw
      outs:
        - data/${item}/processed


  
  # =================================================
  # FEATURE ENGINEERING — MOVIE GENRE (SKLEARN)
  # =================================================
  feature_engineering_movie_genre:
    cmd: python models/movie_genre/src/feature_engineering.py
    deps:
      - models/movie_genre/src/feature_engineering.py
      - data/movie_genre/processed
    params:
      - models.movie_genre.feature_engineering
    outs:
      - data/movie_genre/features
      - artifacts/movie_genre/vectorizer.pkl


  # =================================================
  # FEATURE ENGINEERING — SPAM SMS (TF.KERAS)
  # =================================================
  feature_engineering_spam_sms:
    cmd: python models/spam_sms/src/feature_engineering.py
    deps:
      - models/spam_sms/src/feature_engineering.py
      - data/spam_sms/processed
    params:
      - models.spam_sms.feature_engineering
    outs:
      - data/spam_sms/features
      - artifacts/spam_sms/tokenizer.json

  # =================================================
  # FEATURE ENGINEERING — NO VECTORIZER
  # # =================================================
  # feature_engineering_no_vectorizer:
  #   foreach:
  #     # - fraud_detection
  #     # - customer_churn
  #   do:
  #     cmd: python models/${item}/src/feature_engineering.py
  #     deps:
  #       - models/${item}/src/feature_engineering.py
  #       - data/${item}/processed
  #     params:
  #       - models.${item}.feature_engineering
  #     outs:
  #       - data/${item}/features


  # =================================================
  # MODEL TRAINING — MOVIE GENRE (SKLEARN)
  # =================================================
  model_training_movie_genre:
    cmd: python models/movie_genre/src/model_training.py
    deps:
      - models/movie_genre/src/model_training.py
      - data/movie_genre/features
      - artifacts/movie_genre/vectorizer.pkl
    params:
      - models.movie_genre.training
    outs:
      - artifacts/movie_genre/model.pkl


  # =================================================
  # MODEL TRAINING — SPAM SMS (TF.KERAS SavedModel)
  # =================================================
  model_training_spam_sms:
    cmd: python models/spam_sms/src/model_training.py
    deps:
      - models/spam_sms/src/model_training.py
      - data/spam_sms/features
      - artifacts/spam_sms/tokenizer.json
    params:
      - models.spam_sms.training
    outs:
      - artifacts/spam_sms/model


  # # =================================================
  # # MODEL TRAINING — NO VECTORIZER
  # # =================================================
  # model_training_no_vectorizer:
  #   foreach:
  #     - fraud_detection
  #     # - customer_churn
  #   do:
  #     cmd: python models/${item}/src/model_training.py
  #     deps:
  #       - models/${item}/src/model_training.py
  #       - data/${item}/features
  #     params:
  #       - models.${item}.model
  #     outs:
  #       - artifacts/${item}/random_forest_fraud.joblib


  # =================================================
  # MODEL EVALUATION — WITH VECTORIZER
  # =================================================
  model_evaluation_movie_genre:
    cmd: python models/movie_genre/src/model_evaluation.py
    deps:
      - models/movie_genre/src/model_evaluation.py
      - artifacts/movie_genre/model.pkl        # sklearn
      - artifacts/movie_genre/vectorizer.pkl
      - data/movie_genre/processed
    outs:
      - reports/movie_genre/experiment_info.json

  model_evaluation_spam_sms:
    cmd: python models/spam_sms/src/model_evaluation.py
    deps:
      - models/spam_sms/src/model_evaluation.py
      - artifacts/spam_sms/model          # Keras
      - artifacts/spam_sms/tokenizer.json
      - data/spam_sms/features
    outs:
      - reports/spam_sms/experiment_info.json


  # # =================================================
  # # MODEL EVALUATION — NO VECTORIZER
  # # =================================================
  # model_evaluation_no_vectorizer:
  #   foreach:
      
  #     - fraud_detection
  #     # - customer_churn
  #   do:
  #     cmd: python models/${item}/src/model_evaluation.py
  #     deps:
  #       - models/${item}/src/model_evaluation.py
  #       - artifacts/${item}/random_forest_fraud.joblib
  #       - data/${item}/processed
  #     metrics:
  #       - reports/${item}/metrics.json
  #     outs:
  #       - reports/${item}/experiment_info.json
  model_registration:
    foreach:
      - movie_genre
      - spam_sms
    do:
      cmd: python models/${item}/src/register_model.py
      deps:
      - reports/${item}/experiment_info.json
      - models/${item}/src/register_model.py