stages:

  data_ingestion:
    foreach:
      - movie_genre
      # - credit_card_fraud
      # - customer_churn
    do:
      cmd: python models/${item}/src/data_ingestion.py
      deps:
        - models/${item}/src/data_ingestion.py
        - connections/mongo_connection.py
        - params.yaml
      params:
        - global.random_state
        - global.mongodb
        - models.${item}.data_ingestion
      outs:
        - data/${item}/raw

  data_preprocessing:
    foreach:
      - movie_genre
      # - credit_card_fraud
      # - customer_churn
    do:
      cmd: python models/${item}/src/data_preprocessing.py
      deps:
        - models/${item}/src/data_preprocessing.py
        - data/${item}/raw
      outs:
        - data/${item}/processed

  feature_engineering:
    foreach:
      - movie_genre
      # - credit_card_fraud
      # - customer_churn
    do:
      cmd: python models/${item}/src/feature_engineering.py
      deps:
        - models/${item}/src/feature_engineering.py
        - data/${item}/processed
      params:
        - models.${item}.feature_engineering
      outs:
        - data/${item}/processed
        - artifacts/${item}/vectorizer.pkl

  model_training:
    foreach:
      - movie_genre
      # - credit_card_fraud
      # - customer_churn
    do:
      cmd: python models/${item}/src/model_training.py
      deps:
        - models/${item}/src/model_training.py
        - data/${item}/features
        - artifacts/${item}/vectorizer.pkl
      params:
        - models.${item}.model
      outs:
        - artifacts/${item}/model.pkl

  model_evaluation:
    foreach:
      - movie_genre
      # - credit_card_fraud
      # - customer_churn
    do:
      cmd: python models/${item}/src/model_evaluation.py
      deps:
        - models/${item}/src/model_evaluation.py
        - artifacts/${item}/model.pkl
        - artifacts/${item}/vectorizer.pkl
        - data/${item}/processed
      metrics:
        - reports/${item}/metrics.json
      outs:
        - reports/${item}/experiment_info.json
