global:
  random_state: 42

  mongodb:
    database_name: capstone_db
    url_env_key: MONGODB_URL

models:
  movie_genre:
    data_ingestion:
      collection_name: movie_genre
      test_size: 0.2

    feature_engineering:
      max_features: 6000
      ngram_range: [1, 1]
      min_df: 4
      max_df: 0.95

    training:
      type: linear_svm
      C: 0.6901505730083063

  spam_sms:
    data_ingestion:
      collection_name: spam_csv
    feature_engineering:
      vocab_size: 10000
      max_len: 100
      test_size: 0.2
      random_state: 42
    training:
      embed_dim: 128
      filters: 128
      kernel_sizes: [3,5,7]
      dropout_rate: 0.5
      l2_reg: 0.0001
      learning_rate: 0.001
      batch_size: 64
      epochs: 10
      val_split: 0.1

  fraud_detection:
    data_ingestion:
      collection_name: fraud_transactions
    feature_engineering:
    model:
      type: random_forest
      rf__n_estimators: 200
      rf__min_samples_leaf: 20
      rf__max_features: 0.5
      rf__max_depth: null
      rf__bootstrap: false
     
