global:
  random_state: 42

models:
  movie_genre:
    data_ingestion:
      user: your_mysql_user
      password: your_mysql_password
      host: localhost
      port: 3306
      database: movies_db
      table: movie_plots
      test_size: 0.2

  customer_churn:
    data_ingestion:
      user: your_mysql_user
      password: your_mysql_password
      host: localhost
      port: 3306
      database: telecom_db
      table: customer_churn
      test_size: 0.2

  fraud_detection:
    data_ingestion:
      user: your_mysql_user
      password: your_mysql_password
      host: localhost
      port: 3306
      database: finance_db
      table: credit_card_transactions
      test_size: 0.2
