global:
  random_state: 42

models:
  movie_genre:
    data_ingestion:
      user: mongo_user
      password: mongo_pass
      host: localhost
      port: 27017
      database: movies_db
      collection: movie_genres
      test_size: 0.2
    feature_engineering:
      max_features: 6000
      ngram_range: [1, 1]
      min_df: 4
      max_df: 0.95
    model:
      type: linear_svm
      C: 0.6901505730083063
      

  customer_churn:
    data_ingestion:
      user: mongo_user
      password: mongo_pass
      host: localhost
      port: 27017
      database: telecom_db
      collection: churn_data
      test_size: 0.2

  credit_card_fraud:
    data_ingestion:
      user: mongo_user
      password: mongo_pass
      host: localhost
      port: 27017
      database: finance_db
      collection: fraud_transactions
      test_size: 0.2
